catalog:
  "@ayingott/eslint-config": ^2.0.2
  "@ayingott/prettier-config": ^2.1.3
  "@types/node": ^22.15.3
  bumpp: ^10.1.0
  eslint: ^9.25.1
  lint-staged: ^15.5.1
  prettier: ^3.5.3
  simple-git-hooks: ^2.13.0
  taze: ^19.0.4
  tsdown: ^0.10.1
  typescript: ^5.8.3
  unplugin-auto-import: ^19.1.2
  vitest: ^3.1.2

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
