catalog:
  "@ayingott/eslint-config": ^2.0.5
  "@ayingott/prettier-config": ^2.1.5
  "@types/node": ^24.3.0
  bumpp: ^10.2.3
  eslint: ^9.33.0
  lint-staged: ^16.1.5
  prettier: ^3.6.2
  simple-git-hooks: ^2.13.1
  taze: ^19.1.0
  tsdown: ^0.14.1
  typescript: ^5.9.2
  unplugin-auto-import: ^20.0.0
  vitest: ^3.2.4

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
