catalog:
  "@ayingott/eslint-config": ^2.0.5
  "@ayingott/prettier-config": ^2.1.5
  "@types/node": ^24.2.0
  bumpp: ^10.2.2
  eslint: ^9.32.0
  lint-staged: ^16.1.4
  prettier: ^3.6.2
  simple-git-hooks: ^2.13.1
  taze: ^19.1.0
  tsdown: ^0.13.2
  typescript: ^5.9.2
  unplugin-auto-import: ^19.3.0
  vitest: ^3.2.4

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
